/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AESLibraryJNI */

#ifndef _Included_AESLibraryJNI
#define _Included_AESLibraryJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AESLibraryJNI
 * Method:    GenerateAESKey
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_AESLibraryJNI_GenerateAESKey
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     AESLibraryJNI
 * Method:    SaveKeyToFile
 * Signature: (Ljava/lang/String;[B[B)I
 */
JNIEXPORT jint JNICALL Java_AESLibraryJNI_SaveKeyToFile
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray);

/*
 * Class:     AESLibraryJNI
 * Method:    LoadKeyFromFile
 * Signature: (Ljava/lang/String;[B[B)I
 */
JNIEXPORT jint JNICALL Java_AESLibraryJNI_LoadKeyFromFile
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray);

/*
 * Class:     AESLibraryJNI
 * Method:    AESEncryptFile
 * Signature: ([B[BLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_AESLibraryJNI_AESEncryptFile
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jstring, jstring);

/*
 * Class:     AESLibraryJNI
 * Method:    AESDecryptFile
 * Signature: ([B[BLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_AESLibraryJNI_AESDecryptFile
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
