/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RSAInterop */

#ifndef _Included_RSAInterop
#define _Included_RSAInterop
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RSAInterop
 * Method:    RSA_GenerateKeyPair
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_RSAInterop_RSA_1GenerateKeyPair
  (JNIEnv *, jobject, jint, jstring, jstring, jint);

/*
 * Class:     RSAInterop
 * Method:    RSA_LoadPublicKey
 * Signature: (Ljava/lang/String;[J)I
 */
JNIEXPORT jint JNICALL Java_RSAInterop_RSA_1LoadPublicKey
  (JNIEnv *, jobject, jstring, jlongArray);

/*
 * Class:     RSAInterop
 * Method:    RSA_LoadPrivateKey
 * Signature: (Ljava/lang/String;[J)I
 */
JNIEXPORT jint JNICALL Java_RSAInterop_RSA_1LoadPrivateKey
  (JNIEnv *, jobject, jstring, jlongArray);

/*
 * Class:     RSAInterop
 * Method:    RSA_FreePublicKey
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_RSAInterop_RSA_1FreePublicKey
  (JNIEnv *, jobject, jlong);

/*
 * Class:     RSAInterop
 * Method:    RSA_FreePrivateKey
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_RSAInterop_RSA_1FreePrivateKey
  (JNIEnv *, jobject, jlong);

/*
 * Class:     RSAInterop
 * Method:    RSA_Encrypt
 * Signature: (J[BJ[B[JII)I
 */
JNIEXPORT jint JNICALL Java_RSAInterop_RSA_1Encrypt
  (JNIEnv *, jobject, jlong, jbyteArray, jlong, jbyteArray, jlongArray, jint, jint);

/*
 * Class:     RSAInterop
 * Method:    RSA_Decrypt
 * Signature: (J[BJ[B[JII)I
 */
JNIEXPORT jint JNICALL Java_RSAInterop_RSA_1Decrypt
  (JNIEnv *, jobject, jlong, jbyteArray, jlong, jbyteArray, jlongArray, jint, jint);

/*
 * Class:     RSAInterop
 * Method:    RSA_EncryptFile
 * Signature: (JLjava/lang/String;Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_RSAInterop_RSA_1EncryptFile
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jint, jint);

/*
 * Class:     RSAInterop
 * Method:    RSA_DecryptFile
 * Signature: (JLjava/lang/String;Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_RSAInterop_RSA_1DecryptFile
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jint, jint);

/*
 * Class:     RSAInterop
 * Method:    RSA_GetErrorMessage
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_RSAInterop_RSA_1GetErrorMessage
  (JNIEnv *, jobject, jint);

/*
 * Class:     RSAInterop
 * Method:    RSA_GetMaxPlaintextLength
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_RSAInterop_RSA_1GetMaxPlaintextLength
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
